### ISSUE TITLE
Storage > Use Tenant object instead of tenant id to access storage classes

### ISSUE THREAD

**Issue by OliveGerste** [sap-labs-france/ev-server#2543]
Ideally raising one PR per storage class

**Comment by LucasBrazi06** [comment]
@RohanAntony Good job, you can continue on the other storages.
It would be nice to have a list of checkboxes (one per storage) in the issue description to track the progression.
Thanks.

**Comment by RohanAntony** [comment]
@LucasBrazi06 Thank you

**Comment by RohanAntony** [comment]
Required storage class changes

- [ ] AssetStorage
- [X] BillingStorage
- [ ] CarStorage
- [ ] ChargingStationStorage
- [ ] CompanyStorage
- [ ] ConnectionStorage
- [ ] ConsumptionStorage
- [ ] LoggingStorage
- [ ] NotificationStorage
- [ ] OCPIEndpointStorage
- [X] OCPPStorage (Fixed in another issue)
- [ ] OICPEndpointStorage
- [ ] RegistrationTokenStorage
- [ ] SettingStorage
- [ ] SiteAreaStorage
- [ ] SiteStorage
- [ ] StatisticsStorage
- [ ] TagStorage
- [ ] TenantStorage
- [ ] TransactionStorage
- [ ] UserStorage

**Comment by LucasBrazi06** [comment]
@RohanAntony Just merged Charging Station's PRs, THANKS!
You can undraft the others when you'll be ready.
Put back to In Progress in the meantime.

**Comment by LucasBrazi06** [comment]
@RohanAntony Next. ;-)
