### ISSUE TITLE
How to add charger/ charging stations ? 

### ISSUE THREAD

**Issue by Anmirazik** [sap-labs-france/ev-server#4057]
Hi, im sorry if this sounds absurd , but how can I add charger in my dashboard ? I have read the similar issue someone faced before this but the issue was closed due to inactivity . Can someone help me pls ? 

I read from the previous issue that I need to go to onboard new station and then create new charging registration tokens and copy the URL as shown below 

<img width="1269" alt="image" src="https://user-images.githubusercontent.com/113960675/213507874-f6bda0dc-aaa4-4263-ac53-1b2d27a6a3b6.png">

Once I have copied the URL , what are the next steps ? I'm sorry I'm a totally beginner , I hope someone can help me step by step , thank you , these might be a long issue T_T . 

btw I don't have any EV charger yet so I cant really tested it properly, I just don't know how to connect the charger since there's no guidelines or steps in which I can follow . If no direct solution can be provided can someone at least brief to me how are the process of connecting the actual EV charger to the software ? Thank you so much , your help will be greatly appreciated T_T .

**Comment by An-nasMs1817120893** [comment]
now I have successfully connected to EV simulator thanks to https://github.com/sap-labs-france/ev-server/issues/3048 and https://github.com/sap-labs-france/ev-server/issues/3442

The charging station on the dashboard can be seen below 

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/113960675/213677216-2b0d7e54-1174-4ab0-b80d-2eb32bd9d06d.png">

after successfully connected to the simulator, May I know if there is a method in which we can send random values of energy consumptions to the dashboard so that we can see the graph for energy consumptions ? your help will be greatly appreciated

**Comment by An-nasMs1817120893** [comment]
hi , now im able to change parameters of the charging station and assign the charging station site area . however I cannot start transaction to simulate the data . can someone help me ? the logs are showing the error 

<img width="1105" alt="image" src="https://user-images.githubusercontent.com/113960675/214026984-44ac86b4-0bd8-4d14-89e0-d1d156965a3a.png">

am I missing something ? your help will be greatly appreciated

**Comment by An-nasMs1817120893** [comment]
by the way , what url should I placed in the URL section when changing the charger parameters ? is it the websocket URL which I get from the token when onboard new station ? 

<img width="724" alt="image" src="https://user-images.githubusercontent.com/113960675/214027782-628d852f-19b0-4806-8b39-622ce2bf0914.png">

**Comment by Zakichanu** [comment]
Any news on what "URL" means?
